# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

dotenv: [.env]

vars:
  CA_CRT_SECRET: fd5dd252-b961-488c-b34a-b3aa014951fb
  CA_KEY_SECRET: abf538c5-cdb2-454b-a43d-b3aa014961df
  SUFFIX: /16
  CHOWN: root:root
  ETC_NEBULA: /etc/nebula
  NODES:
    map:
      lighthouse-01: 10.10.0.1
      corellia: 10.10.2.1
      tablet: 10.10.2.2
      workmac: 10.10.2.3
      hoth: 10.10.2.4
      steamdeck: 10.10.2.5
      unimatrix-01: 10.10.42.11
      unimatrix-02: 10.10.42.12
      unimatrix-03: 10.10.42.13
      drone-01: 10.10.42.21
      drone-02: 10.10.42.22
      drone-03: 10.10.42.23
      drone-04: 10.10.42.24

tasks:
  make:ca:
    status:
      - test -f ca.crt
      - test -f ca.key
    generates: [ca.crt, ca.key]
    cmd: nebula-cert ca -version 1 -name "Borg Collective"

  fetch:ca:
    status:
      - test -f ca.crt
      - test -f ca.key
    generates: [ca.crt, ca.key]
    cmds:
      - >
        bws secret get "{{.CA_CRT_SECRET}}"
        | jq --raw-output .value
        > ca.crt
      - >
        bws secret get "{{.CA_KEY_SECRET}}"
        | jq --raw-output .value
        > ca.key

  sign:*:
    deps: [fetch:ca]
    sources: [ca.crt, ca.key]
    generates: ['{{.NAME}}.crt', '{{.NAME}}.key']
    vars:
      NAME: '{{ index .MATCH 0 }}'
      IP: '{{ get .NODES .NAME }}'
    cmd: nebula-cert sign -version 1 -name "{{.NAME}}" -ip "{{.IP}}{{.SUFFIX}}"

  deploy-remote:*:
    requires:
      vars: [TYPE]
    vars:
      NAME: '{{ index .MATCH 0 }}'
    deps: ['sign:{{.NAME}}']
    sources: [ca.crt, '{{.NAME}}.crt', '{{.NAME}}.key', '{{.TYPE}}.yml']
    cmds:
      - >
        rsync "{{.NAME}}.crt" "{{.NAME}}.key" "ca.crt" "{{.TYPE}}.yml"
        {{.NAME}}:/tmp/
      - |
        ssh {{.NAME}} "
          sudo mkdir {{.ETC_NEBULA}}
          sudo mv /tmp/ca.crt {{.ETC_NEBULA}}
          sudo mv /tmp/{{.NAME}}.crt {{.ETC_NEBULA}}/host.crt
          sudo mv /tmp/{{.NAME}}.key {{.ETC_NEBULA}}/host.key
          sudo mv /tmp/{{.TYPE}}.yml {{.ETC_NEBULA}}/config.yml
          sudo chown -R {{.CHOWN}} {{.ETC_NEBULA}}
          sudo systemctl enable --now nebula
          sudo systemctl restart nebula
        "

  deploy-local:*:
    requires:
      vars: [TYPE]
    vars:
      NAME: '{{ index .MATCH 0 }}'
    deps: ['sign:{{.NAME}}']
    sources: [ca.crt, '{{.NAME}}.crt', '{{.NAME}}.key', '{{.TYPE}}.yml']
    generates:
      - '{{.ETC_NEBULA}}/config.yml'
      - '{{.ETC_NEBULA}}/host.crt'
      - '{{.ETC_NEBULA}}/host.key'
      - '{{.ETC_NEBULA}}/ca.crt'
    cmds:
      - rsync "{{.NAME}}.crt" "{{.NAME}}.key" "ca.crt" "{{.TYPE}}.yml" /tmp/
      - sudo mkdir -p {{.ETC_NEBULA}}
      - sudo mv /tmp/ca.crt {{.ETC_NEBULA}}
      - sudo mv /tmp/{{.TYPE}}.yml {{.ETC_NEBULA}}/config.yml
      - sudo mv /tmp/{{.NAME}}.crt {{.ETC_NEBULA}}/host.crt
      - sudo mv /tmp/{{.NAME}}.key {{.ETC_NEBULA}}/host.key
      - sudo chown -R {{.CHOWN}} {{.ETC_NEBULA}}
