# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

dotenv: [.env]

vars:
  NEBULA_CERT_ARGS: -version 1
  CA_CRT_SECRET: fd5dd252-b961-488c-b34a-b3aa014951fb
  CA_KEY_SECRET: abf538c5-cdb2-454b-a43d-b3aa014961df
  SUFFIX: /16
  CHOWN: root:root
  ETC_NEBULA: /etc/nebula
  NODES:
    map:
      lighthouse-01: 10.10.0.1
      corellia: 10.10.2.1
      tablet: 10.10.2.2
      workmac: 10.10.2.3
      hoth: 10.10.2.4
      steamdeck: 10.10.2.5
      unimatrix-01: 10.10.42.11
      unimatrix-02: 10.10.42.12
      unimatrix-03: 10.10.42.13
      drone-01: 10.10.42.21
      drone-02: 10.10.42.22
      drone-03: 10.10.42.23
      drone-04: 10.10.42.24

tasks:
  conn:local:
    internal: true
    requires:
      vars: [CMD]
    cmd: '{{.CMD}}'

  conn:ssh:
    internal: true
    requires:
      vars: [HOST, CMD]
    cmd: ssh {{.HOST}} "{{.CMD}}"

  make:ca:
    status:
      - test -f ca.crt
      - test -f ca.key
    generates: [ca.crt, ca.key]
    cmd: nebula-cert ca {{.NEBULA_CERT_ARGS}} -name "Borg Collective"

  fetch:ca:
    status:
      - test -f ca.crt
      - test -f ca.key
    generates: [ca.crt, ca.key]
    cmds:
      - >
        bws secret get "{{.CA_CRT_SECRET}}"
        | jq --raw-output .value
        > ca.crt
      - >
        bws secret get "{{.CA_KEY_SECRET}}"
        | jq --raw-output .value
        > ca.key

  sign:*:
    deps: [fetch:ca]
    sources: [ca.crt, ca.key]
    generates: ['{{.NAME}}.crt', '{{.NAME}}.key']
    vars:
      NAME: '{{ index .MATCH 0 }}'
      IP: '{{ get .NODES .NAME }}'
    cmd: nebula-cert sign {{.NEBULA_CERT_ARGS}} -name "{{.NAME}}" -ip "{{.IP}}{{.SUFFIX}}"

  deploy:*:*:
    requires:
      vars: [TYPE]
    vars:
      CONN: '{{ index .MATCH 0 }}'
      HOST: '{{ index .MATCH 1 }}'
      DEST: '{{if eq .CONN "ssh"}}{{.HOST}}:/tmp/{{else}}/tmp/{{end}}'
    preconditions:
      - sh: 'echo "{{.TYPE}}" | grep -E "^(lighthouse|node)$"'
        msg: 'TYPE must be lighthouse or node'
      - sh: 'echo "{{.CONN}}" | grep -E "^(local|ssh)$"'
        msg: 'CONN must be local or ssh'
    deps: ['sign:{{.HOST}}']
    sources: [ca.crt, '{{.HOST}}.crt', '{{.HOST}}.key', '{{.TYPE}}.yml']
    cmds:
      - rsync "{{.HOST}}.crt" "{{.HOST}}.key" "ca.crt" "{{.TYPE}}.yml" {{.DEST}}
      - task: conn:{{.CONN}}
        vars:
          HOST: '{{.HOST}}'
          CMD: |
            sudo mkdir -p {{.ETC_NEBULA}}
            sudo mv /tmp/ca.crt {{.ETC_NEBULA}}
            sudo mv /tmp/{{.HOST}}.crt {{.ETC_NEBULA}}/host.crt
            sudo mv /tmp/{{.HOST}}.key {{.ETC_NEBULA}}/host.key
            sudo mv /tmp/{{.TYPE}}.yml {{.ETC_NEBULA}}/config.yml
            sudo chown -R {{.CHOWN}} {{.ETC_NEBULA}}
