# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

vars:
  CHOWN: root:root
  ETC_NEBULA: /etc/nebula
  NODES:
    map:
      lighthouse-01: 10.10.0.1/16
      corellia: 10.10.2.1/16
      tablet: 10.10.2.2/16
      workmac: 10.10.2.3/16
      hoth: 10.10.2.4/16

tasks:
  make:ca:
    status:
      - test -f ca.crt
      - test -f ca.key
    generates: [ca.crt, ca.key]
    cmd: nebula-cert ca -version 1 -name "Borg Collective"

  sign:*:
    deps: [make:ca]
    sources: [ca.crt, ca.key]
    generates: ['{{.NAME}}.crt', '{{.NAME}}.key']
    vars:
      NAME: '{{ index .MATCH 0 }}'
      IP: '{{ get .NODES .NAME }}'
    cmd: nebula-cert sign -version 1 -name "{{.NAME}}" -ip "{{.IP}}"

  deploy-remote:*:
    requires:
      vars: [TYPE]
    vars:
      NAME: '{{ index .MATCH 0 }}'
    deps: ['sign:{{.NAME}}']
    sources: [ca.crt, '{{.NAME}}.crt', '{{.NAME}}.key', '{{.TYPE}}.yml']
    cmds:
      - >
        rsync "{{.NAME}}.crt" "{{.NAME}}.key" "ca.crt" "{{.TYPE}}.yml"
        {{.NAME}}:/tmp/
      - |
        ssh {{.NAME}} "
          sudo mv /tmp/ca.crt /etc/nebula/
          sudo mv /tmp/{{.NAME}}.crt /etc/nebula/host.crt
          sudo mv /tmp/{{.NAME}}.key /etc/nebula/host.key
          sudo mv /tmp/{{.TYPE}}.yml /etc/nebula/config.yml
          sudo chown -R root:root /etc/nebula
          sudo systemctl enable --now nebula
          sudo systemctl restart nebula
        "

  deploy-local:*:
    requires:
      vars: [TYPE]
    vars:
      NAME: '{{ index .MATCH 0 }}'
    deps: ['sign:{{.NAME}}']
    sources: [ca.crt, '{{.NAME}}.crt', '{{.NAME}}.key', '{{.TYPE}}.yml']
    generates:
      - '{{.ETC_NEBULA}}/config.yml'
      - '{{.ETC_NEBULA}}/host.crt'
      - '{{.ETC_NEBULA}}/host.key'
      - '{{.ETC_NEBULA}}/ca.crt'
    cmds:
      - sudo mkdir -p {{.ETC_NEBULA}}
      - sudo cp ca.crt {{.ETC_NEBULA}}
      - sudo cp {{.TYPE}}.yml {{.ETC_NEBULA}}/config.yml
      - sudo cp {{.NAME}}.crt {{.ETC_NEBULA}}/host.crt
      - sudo cp {{.NAME}}.key {{.ETC_NEBULA}}/host.key
      - sudo chown -R {{.CHOWN}} {{.ETC_NEBULA}}
